server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  application:
    name: ai-writing-backend

  cache:
    type: simple

groq:
  api:
    base-url: https://api.groq.com/openai/v1
    key: ${GROQ_API_KEY}
    model-fast: llama-3.1-8b-instant
    model-smart: llama-3.3-70b-versatile
    max-tokens: 300
    timeout-seconds: 10

# firebase:
#   credentials-path: src/main/resources/firebase-service-account.json
#   project-id: timetable-446ca

rate-limit:
  free-rpm: 20
  pro-rpm: 120

management:
  endpoints:
    web:
      exposure:
        include: health,info
